const express = require('express');
const mongoose = require('mongoose');
const TVSeries = require('./TVSeries');
const MovieSeries = require('./MovieSeries');
const path = require('path');
const app = express();
mongoose.connect('mongodb://localhost:27017/moviesdb');
app.use(express.static(__dirname));


app.get('/index.html', (req, res) => {
  res.sendFile(path.join(__dirname, 'index.html'));
});

app.get('/', (req, res) => {
  res.sendFile(path.join(__dirname, 'index.html'));
});
app.get('/index.html', (req, res) => {
  res.sendFile(path.join(__dirname, 'index.html'));
});
app.get('/movies', (req, res) => {
  res.sendFile(path.join(__dirname, 'MovieSeriesReviews.html'));
});
app.get('/tv', (req, res) => {
  res.sendFile(path.join(__dirname, 'TelevisionSeriesReviews.html'));
});


const seriesArray = [
{
    name: "The Last of Us: Season 1 (2023) - 8.1",
    episodes: [
        { title: "When You're Lost in the Darkness - 9.1", poster: "https://m.media-amazon.com/images/M/MV5BZmQzM2M5ZTQtZmZiNi00NTU2LWFhNDUtOWQ5MmExZGYwYTExXkEyXkFqcGc@._V1_QL75_UX388_.jpg", summary: "In 2003, a fungal outbreak of Cordyceps causes a global collapse. Joel, a smuggler, tragically loses his daughter Sarah on outbreak day. Twenty years later, in a quarantine zone, Joel and partner Tess are hired to smuggle a teenage girl, Ellie, who may be immune to the infection, across the country for the rebel group Fireflies." },
        { title: "Infected - 9.2", poster: "https://m.media-amazon.com/images/M/MV5BNTE5OTA2OWUtMjgxYy00N2M2LTkxYzMtMzAyZDdhM2JhYTBmXkEyXkFqcGc@._V1_QL75_UX388_.jpg", summary: "Joel, Tess, and Ellie travel through ruined Boston. Ellie’s immunity is confirmed when she resists infection after a bite. Tess sacrifices herself to buy time when she is bitten, urging Joel to take Ellie west to the Fireflies." },
        { title: "Long Long Time - 7.7", poster: "https://m.media-amazon.com/images/M/MV5BMjI1NWRkYzAtN2RkNy00NTljLThjOWItYjE0MzRiYzhhMjFmXkEyXkFqcGc@._V1_QL75_UX388_.jpg", summary: "The story shifts to Bill and Frank, two survivors who form a decades-long relationship while building a secure life in the apocalypse. Joel later finds their home after their deaths, receiving supplies and a car to continue the journey with Ellie." },
        { title: "Please Hold to My Hand - 7.0", poster: "https://m.media-amazon.com/images/M/MV5BMmY0NDY3N2YtY2JkOS00NmNjLWE5ZDAtNjEyNzMwYzUyYTQ2XkEyXkFqcGc@._V1_QL75_UX328_.jpg", summary: "Joel and Ellie travel through Kansas City, where they are ambushed by hunters. They bond during downtime, with Ellie starting to break Joel’s hardened exterior. The episode ends with them being held at gunpoint by two young brothers, Henry and Sam." },
        { title: "Endure and Survive - 8.5", poster: "https://m.media-amazon.com/images/M/MV5BZGI4NzliZTUtMjhjNS00MWVjLTliMTItNmM2MDNlNjIxY2I5XkEyXkFqcGc@._V1_QL75_UX388_.jpg", summary: "Henry explains he and Sam are hunted by revolutionaries who overthrew FEDRA. Joel helps them escape, but tragedy strikes when Sam is bitten and turns. Henry, devastated, kills Sam and then himself. Joel and Ellie bury them before moving on." },
        { title: "Kin - 9.7", poster: "https://m.media-amazon.com/images/M/MV5BNzJkZWU3ZTctM2FiMC00NmJjLTkxZWQtMDRhNDAyMWEwOWJhXkEyXkFqcGc@._V1_QL75_UX328_.jpg", summary: "Joel and Ellie reunite with Joel’s brother Tommy in Wyoming, now living in a thriving settlement. Joel, wracked with doubt about his ability to protect Ellie, asks Tommy to take her to the Fireflies. Ellie confronts him about loss and abandonment, and Joel recommits to the mission." },
        { title: "Left Behind - 3.3", poster: "https://m.media-amazon.com/images/M/MV5BYmEyYWI2ODYtMWE4Yi00NzYzLTg2NzMtYzczOTkwYzE3OTU5XkEyXkFqcGc@._V1_QL75_UX328_.jpg", summary: "Through flashbacks, Ellie recalls her time in a Boston military school with her best friend (and love) Riley. Riley shows Ellie a mall where they share joy and a kiss, but both are bitten. Riley chooses to stay with Ellie until the end — though Ellie survives and Riley does not." },
        { title: "When We Are in Need - 9.0", poster: "https://m.media-amazon.com/images/M/MV5BOWQ1YWM3YzktOGRkNC00NjY5LThhYmYtYzgwYzJlZjcwNTI0XkEyXkFqcGc@._V1_QL75_UX328_.jpg", summary: "Joel, injured, relies on Ellie to find food and medicine. She encounters David, leader of a seemingly kind group that is revealed to be cannibalistic. After David tries to manipulate and assault her, Ellie brutally kills him. Traumatized, she is comforted by Joel, who calls her “baby girl” — echoing his lost daughter." },
        { title: "Look for the Light - <b> Perfect Score </b>", poster: "https://m.media-amazon.com/images/M/MV5BNWQyN2FkOTYtMDQ5MC00ZWZhLTgxN2QtYWZhNzlhMzJjNjI5XkEyXkFqcGc@._V1_QL75_UX328_.jpg", summary: "Joel and Ellie reach the Fireflies. Doctors prepare to operate on Ellie, intending to remove the Cordyceps in her brain to create a cure — but it will kill her. Unwilling to lose another “daughter,” Joel massacres the Fireflies, rescues Ellie, and kills Marlene, their leader. He lies to Ellie, telling her the Fireflies had stopped searching for a cure. The season ends with Ellie asking Joel if he’s telling the truth — and Joel insisting he is."} 
    ]
    },
    {
    name: "The Last of Us: Season 2 (2025)- 4.7",
    episodes: [
        { title: "Future Days - 6.0", poster: "https://m.media-amazon.com/images/M/MV5BMGFhY2NmNTEtMmFkYS00MDViLThjMjUtNmRlYTBlMjcyZWUyXkEyXkFqcGc@._V1_QL75_UX328_.jpg", summary: "Five years after Season 1, Joel and Ellie have settled in Jackson, Wyoming, but their relationship is strained following Joel’s lie about saving her at the Firefly hospital.  Joel attends therapy, seeking redemption, while Ellie grows closer to Dina but remains emotionally distant.  Across the season opener, we’re introduced to Abby, who vows revenge on Joel for killing her father—a familiar face from the Fireflies." },
        { title: "Infected - 4.5", poster: "https://m.media-amazon.com/images/M/MV5BZjUyYzM3MjItNGY4Yi00NTk4LTliYTgtYjg3ODZkMDExNmExXkEyXkFqcGc@._V1_QL75_UX328_.jpg", summary: "Joel and Dina patrol Jackson when Abby’s group triggers an infected horde attack that overwhelms the settlement.  Amid the chaos, Joel is ambushed and brutally killed by Abby, setting off a chain reaction of grief and vengeance." },
        { title: "The Path - 3.2", poster: "https://m.media-amazon.com/images/M/MV5BNjdiNjhiNzAtYzQ4Yy00ZmYwLWIyMTctODY2OWEyNTUxOWI3XkEyXkFqcGc@._V1_QL75_UX328_.jpg", summary: "Ellie and Dina enter Seattle amid the WLF–Seraphite conflict.  Ellie reveals her immunity to Dina, a pivotal emotional moment, while the chaos of war surrounds them."},
        { title: "Day One - 2.2", poster: "https://m.media-amazon.com/images/M/MV5BZTBmNGJmMWQtZjY2OC00NmQxLTkwMGMtZTEzMGZjMzk5ODBhXkEyXkFqcGc@._V1_QL75_UX328_.jpg", summary: "Ellie and Dina enter Seattle amid the WLF–Seraphite conflict.  Ellie reveals her immunity to Dina, a pivotal emotional moment, while the chaos of war surrounds them."},
        { title: "Feel Her Love - 6.1", poster: "https://m.media-amazon.com/images/M/MV5BZWIzN2NjZTctYzcwZS00NTlmLWE0OWYtYWJmMGIxZTY0YTFmXkEyXkFqcGc@._V1_QL75_UX400_.jpg", summary: "Ellie and Dina search for Abby’s whereabouts, locating Nora to gather information.  The episode reinforces Ellie’s immunity (thwarting the spread through spores) and features intense horror elements with Ellie’s emotional instability becoming more pronounced,"},
        { title: "The Price - 9.1", poster: "https://m.media-amazon.com/images/M/MV5BMDFhMDEzYzMtMDg2NS00OGVkLWI3YzgtN2E3NGYyOGQwMmYxXkEyXkFqcGc@._V1_QL75_UX388_.jpg",summary: "A flashback reveals the evolving dynamic between Joel and Ellie in Jackson over many years, marked by growing tension and Joel’s protective deception.  Their bond fractures when Joel’s lie—a result of him killing Eugene rather than letting him turn—comes to light. They confront the truth but the revelation fractures their connection."},
        { title: "Convergence - 2.0", poster: "https://m.media-amazon.com/images/M/MV5BMjY5ZWY2ZjYtZjQ3Zi00MjBmLWFmYjUtYWVjZTZiMzA1N2NmXkEyXkFqcGc@._V1_QL75_UX402_.jpg", summary: "On their third day in Seattle, Ellie (with Dina and Jesse) continues to hunt Abby amid a major WLF–Seraphite battle.  Ellie brutally kills Owen and Mel—only to realize Mel is pregnant, intensifying her trauma.  As Jessie and Tommy arrive, Abby ambushes them, killing Jesse and putting Tommy’s life on the line. Ellie pleads for mercy, offering herself instead—but Abby responds with, “I let you live. And you wasted it,” following which a gunshot rings out and the screen cuts to black.  In a final shift, we glimpse Abby waking up in a flashback titled “Seattle, Day One”, marking a narrative pivot to her perspective."}
    ]
    },
    {
    name: "Righeous Gemstones: Season 1 (2019) - 7.6", 
    episodes: [
        { title: "S01E01 - The Righteous Gemstones - 8.1", poster: "https://m.media-amazon.com/images/M/MV5BNzZkMWY2ZTktZWI2OC00M2Q0LWE2N2YtZjg4OTg0YTYxYzM1XkEyXkFqcGc@._V1_QL75_UX328_.jpg", summary: "The Gemstones return from a mass baptism in China. Jesse’s wild lifestyle catches up with him when he’s blackmailed over a scandalous video. His son Gideon secretly plots against him with criminals. The family’s dysfunction is laid bare."},
        { title: "S01E02 - Is This the Man Who Made the Earth Trenble - 7.5", poster: "https://m.media-amazon.com/images/M/MV5BZDBlN2EzOTYtYTU1MS00ZjRhLWI1MTYtYTkxMWZlYmYyY2NiXkEyXkFqcGc@._V1_QL75_UX166_.jpg", summary: "Jesse, Kelvin, and Judy try to confront the blackmailers but botch the payoff attempt, escalating the threat. Eli reflects on the legacy of his late wife Aimee-Leigh. Gideon’s betrayal deepens."},
        { title: "S01E03 - They Are Weak, But He Is Strong - 7.4", poster: "https://m.media-amazon.com/images/M/MV5BN2FmZjE3NDgtODFiNy00NDI4LTk5ZGEtOWFmZDVkYjRlNzYzXkEyXkFqcGc@._V1_QL75_UX166_.jpg", summary: "Baby Billy Freeman, Aimee-Leigh’s brother, re-enters the family’s orbit, scheming to get a place in the church. Judy, desperate for recognition, is drawn to his manipulative promises. Meanwhile, the Gemstone kids struggle with unity."},
        { title: "S01E04 - Wicked Lips - 6.1", poster: "https://m.media-amazon.com/images/M/MV5BN2FhN2E0NGUtMmJlNi00ZjIwLTkxMmMtYzYxNTI0N2U3ZGM3XkEyXkFqcGc@._V1_QL75_UX328_.jpg", summary: "Kelvin’s youth ministry, “God Squad,” faces trouble when one of his disciples begins questioning him. Jesse tries to regain control of the blackmail situation. Judy’s frustrations with being overlooked boil over, pushing her closer to Baby Billy."},
        { title: "S01E05 - Interlude - 8.5", poster: "https://m.media-amazon.com/images/M/MV5BOTk1OWVkZmMtMTVjYy00NmU3LWFlYzItMDNkNmE1N2YxOGIyXkEyXkFqcGc@._V1_QL75_UX388_.jpg", summary: "Flashback episode: the Gemstone family in 1989. We see Aimee-Leigh alive, performing with Baby Billy as a Christian singing duo. Eli is hesitant about the show-business lifestyle, while Baby Billy resents Aimee-Leigh’s choice of family over fame. This episode gives depth to the family’s roots and traumas."},
        { title: "S01E06 -  Now the Sons of Eli Were Worthless Men - 7.3", poster: "https://resizing.flixster.com/ZLCiruD_rKx6Lw5L08pziSfyeYE=/fit-in/705x460/v2/https://resizing.flixster.com/-XZAfHZM39UwaGJIFWKAE8fS0ak=/v3/t/assets/p17161171_e_v9_aa.jpg", summary: "The blackmail plot spirals into violence. The Gemstones discover shocking betrayals within their inner circle. Jesse struggles with Gideon’s rebellion. Kelvin’s faith is tested as he loses influence over his disciples."},
        { title: "S01E07 - And Yet One of You Is a Devil - 7.4", poster: "https://m.media-amazon.com/images/M/MV5BMzBiMmI4NmQtNTdiMi00NzUwLWEzMWUtNTg3ZjUzM2Y5ZGY4XkEyXkFqcGc@._V1_QL75_UX291_.jpg", summary: "The truth about Gideon’s involvement with the blackmailers comes to light. Eli’s trust in his children crumbles. Baby Billy deepens his manipulation of Judy. The family is on the brink of collapse as enemies close in."},
        { title: "S01E08 - But the Righteous Will See Their Fall (2019) - 8.7", poster: "https://m.media-amazon.com/images/M/MV5BYjZkNGMyYmEtODU0Yi00ZDZjLThlOWItOTZkYzI1YjljODliXkEyXkFqcGc@._V1_QL75_UX291_.jpg", summary: "In a climactic showdown, the Gemstones confront their enemies and each other. Jesse fights to reclaim his family’s honor. Judy breaks free from Baby Billy’s influence. Eli must decide whether to forgive or sever ties with his children. The season ends with the family fractured but determined to rebuild."},
        { title: "S01E09 - Better is the End of a Thing Than Its Beginning (2019) - 8.0", poster: "https://m.media-amazon.com/images/M/MV5BZjA5ZWJiYTgtZDJkZC00ODg1LWI0YjktZGJiNDMwZjY0N2M0XkEyXkFqcGc@._V1_QL75_UX402_.jpg", summary: "The Gemstones attempt to heal their fractured relationships. Jesse and Gideon find a tentative path to reconciliation. Judy asserts her independence from Baby Billy. Eli reflects on the cost of their lifestyle and the hope for redemption."}
    ]
    },
    {
    name: "Cyberpunk: Edgerunners: Season 1 (2022) - 8.0",
    episodes: [
        { title: "S01E01 - Let You Down - 7.6", poster: "https://m.media-amazon.com/images/M/MV5BZDFjYjUyY2UtODZiYi00MTI2LTgxZmItNmI5ZjBiNDE4MWI1XkEyXkFqcGc@._V1_QL75_UX388_.jpg", summary: "David Martinez, a gifted but poor student at the prestigious Arasaka Academy, struggles to fit in. After his mother dies in a tragic drive-by accident and he’s left with nothing, he discovers military-grade cyberware, a Sandevistan implant, that changes his life."},
        { title: "S01E02 - Like A Boy - 8.8", poster: "https://m.media-amazon.com/images/M/MV5BYmFiOTljODgtNGJkNy00ODhhLWEyYmItYmNhNTYyYmQyZTkzXkEyXkFqcGc@._V1_QL75_UX388_.jpg", summary: "David installs the Sandevistan, giving him superhuman speed. He meets Lucy, a mysterious netrunner, and is drawn into her world of edgerunners — mercenaries who live on the edge of survival. Their bond begins forming as they pull off small jobs together."},
        { title: "S01E03 - Smooth Criminal (2022) - 7.5", poster: "https://m.media-amazon.com/images/M/MV5BYWU1NjE5ZWYtNjZkMi00ODhkLTgxMGQtNDgyOGI2YjFkOWVlXkEyXkFqcGc@._V1_QL75_UX388_.jpg", summary: "Lucy introduces David to Maine’s edgerunner crew. Initially mistrusted, David proves himself by using the Sandevistan in combat. He begins finding belonging within the group, even as he risks his sanity and health from overusing the implant."},
        { title: "S01E04 - Lucky You (2022) - 7.4", poster: "https://m.media-amazon.com/images/M/MV5BYmEwMjJiNjQtYjczNS00YTE3LTk2ODMtMTIyOGY2MThhMTc5XkEyXkFqcGc@._V1_QL75_UX388_.jpg", summary: "David trains under Maine’s crew and starts fitting in. He grows closer to Lucy, but learns more about the dangers of their lifestyle. Maine warns David about cyberpsychosis, a mental breakdown caused by too much augmentation."},
        { title: "S01E05 - All Eyez on Me (2022) - 7.8", poster: "https://m.media-amazon.com/images/M/MV5BM2MwZjdjODMtMzRkMi00ZDcwLTk3ZTUtZDFlNDkxYWVhYTdkXkEyXkFqcGc@._V1_QL75_UX388_.jpg", summary: "The crew takes on a dangerous mission. Maine starts showing early signs of cyberpsychosis, lashing out unpredictably. David and Lucy’s relationship deepens, though their dreams clash — Lucy longs to escape to the Moon."},
        { title: "S01E06 - Girl on Fire (2022) - 9.1", poster: "https://m.media-amazon.com/images/M/MV5BYjc5NmUzNGUtODE5ZS00MTkwLTg1M2ItOWY5NDA4MTYwYzQ2XkEyXkFqcGc@._V1_QL75_UX388_.jpg", summary: "Maine’s descent into cyberpsychosis becomes uncontrollable. During a mission, he loses himself completely. In a heartbreaking end, Maine sacrifices himself to protect his team, leaving David shaken and forcing him to step up as a leader."},
        { title: "S01E07 - Stronger (2022) - 7.2", poster: "https://m.media-amazon.com/images/M/MV5BZGVmYmFjNjUtZTdkOS00YjI2LWFmNTMtNzcyYWNiMTNjNjA5XkEyXkFqcGc@._V1_QL75_UX388_.jpg", summary: "Time skip: David has grown into a hardened edgerunner leader, with far more chrome in his body and greater reliance on implants. He and Lucy are a couple, but cracks show in their lives. Lucy hides secrets about Arasaka’s interest in David."},
        { title: "S01E08 - Stay (2022) - 7.7", poster: "https://m.media-amazon.com/images/M/MV5BM2YyYzYyYjItYzYxNy00ZGI3LWI3ZTAtYjY0YTIyMjM0ZGM3XkEyXkFqcGc@._V1_QL75_UX388_.jpg", summary: "The crew is targeted by Arasaka. Faraday, a fixer with his own agenda, manipulates events to pit Militech and Arasaka against each other. Lucy tries to protect David from becoming a corporate pawn, but he is already too deep in the edgerunner lifestyle."},
        { title: "S01E09 - Humanity (2022) - 7.3", poster: "https://m.media-amazon.com/images/M/MV5BNDc5MzMyNGMtMDY0OS00ZTFhLWE2N2MtZjkzOGI3ODcxNmJhXkEyXkFqcGc@._V1_QL75_UX388_.jpg", summary: "David pushes his body beyond safe limits, installing the massive cyber-skeleton Arasaka wants to test. Lucy is captured. David, despite increasing signs of cyberpsychosis, refuses to back down, determined to rescue her."},
        { title: "S01E10 - My Moon, My Man (2022) - 9.1", poster: "https://m.media-amazon.com/images/M/MV5BZjA0M2QyZmQtNGY1Ny00YmI4LTlkOWEtMzBiMzYzZWUyZDA2XkEyXkFqcGc@._V1_QL75_UX383_.jpg", summary: "David and his crew launch a desperate assault to save Lucy from Arasaka Tower. In a brutal showdown, David battles Adam Smasher, Arasaka’s legendary cyborg enforcer. Overwhelmed, David makes a final stand, buying Lucy’s freedom. He dies heroically, consumed by cyberpsychosis and violence. In the end, Lucy escapes to the Moon, fulfilling her dream — but alone, mourning David."}
    ]    
    },
    {
    name: "Iron Heart (2024) - 3.9",
    episodes: [
        { title: "S01E01 - Take Me Home - 2.7", poster: "https://m.media-amazon.com/images/M/MV5BZjc5MzlkOWUtZTk2OC00MmZkLWJjOTMtMGI4MjY5ZDU2MjY1XkEyXkFqcGc@._V1_QL75_UX328_.jpg", summary: "Riri Williams is expelled from MIT, returns to Chicago, and joins Parker Robbins’ (The Hood’s) crew while secretly creating an AI of her late friend Natalie."},
        { title: "S01E02 - Will the Real Natalie Please Stand Up - 2.1", poster: "https://m.media-amazon.com/images/M/MV5BZTRkMzNiNWQtMzQwMC00MzUzLTg3MjUtZTE0YWExYjc3ZmIxXkEyXkFqcGc@._V1_QL75_UX328_.jpg", summary: "Riri officially becomes part of Parker’s gang and helps on a heist, but the reveal of her Natalie AI sparks tension and Parker’s magic begins to worry her."},
        { title: "S01E03 - We in Danger, Girl - 4.8", poster: "https://m.media-amazon.com/images/M/MV5BYmU2MzVhMzctYTQ2MS00MmU3LTlmZTgtZDU2M2ExNGM4ZDUxXkEyXkFqcGc@._V1_QL75_UX435_.jpg", summary: "A mission against an agritech company spirals out of control; John dies during the chaos, and Riri chooses not to save him, deepening divisions in the crew."},
        { title: "S01E04 - Bad Magic - 5.8", poster: "https://m.media-amazon.com/images/M/MV5BNjAxOTdlMTEtMWM5Yi00OGQ4LTg0ZWYtMjMzNjYwNWQ3YzNhXkEyXkFqcGc@._V1_QL75_UX389_.jpg", summary: "The origins of Parker’s cloak are traced to dark magic; Xavier demands Riri delete the AI; Parker manipulates the gang into blaming Riri for John’s death."},
        { title: "S01E05 - Karma's a Glitch - 3.1", poster: "https://m.media-amazon.com/images/M/MV5BYTMyNTgyZjctZjY4OC00NTc5LTk5YzYtYTQxMjY5ZWY3MzhkXkEyXkFqcGc@._V1_QL75_UX522_.jpg", summary: "Riri rebuilds her suit with magical enhancements, reconciles with her family, and chooses to delete the Natalie AI, marking a painful emotional reset."},
        { title: "S01E06 - The Past Is the Past - 5.1", poster: "https://m.media-amazon.com/images/M/MV5BNWNiZWQzZWQtOWZiMi00OWRlLTk3M2QtN2M0MmUzYWUyODI5XkEyXkFqcGc@._V1_QL75_UX522_.jpg", summary: "It’s revealed Parker’s cloak came from a deal with Mephisto; Riri defeats Parker, but Mephisto tempts her with Natalie’s return—and she accepts his dark bargain."}
    ]
    },
    {
    name: "Black Mirror : Round 1 - 8.8",
    episodes: [
        {title: "Black Mirror - S03E01 - Nosedive (2016) - 9.0", poster: "https://upload.wikimedia.org/wikipedia/en/d/d9/Black_Mirror_-_Nosedive.png", summary: "In a pastel, Instagram-like future where everyone rates each social interaction on a 5-star system, social status is determined by one’s overall rating. Lacie Pound (Bryce Dallas Howard) is obsessed with boosting her 4.2 rating to a 4.5 so she can afford a luxury apartment. She rehearses smiles, posts carefully curated photos, and tries to impress highly rated people. When her childhood friend Naomi (4.8) asks her to be maid of honor at her wedding, Lacie sees it as the perfect chance to raise her score. But as she travels to the wedding, a series of misfortunes, flight delays, arguments, and car troubles cause her rating to plummet. Strangers rate her poorly for minor outbursts, and her carefully constructed persona crumbles. By the time she arrives at the wedding (disheveled, exhausted, and with a dangerously low rating), she crashes the event, gives an unhinged speech, and is ejected. Her score bottoms out, leading to her arrest and imprisonment. In her cell, stripped of ratings, Lacie finally feels free, trading insults and laughter with another prisoner without worrying about judgment."},
        { title: "Black Mirror - S03E02 - Playtest (2016) - 8.0", poster: "https://upload.wikimedia.org/wikipedia/en/7/76/Black_Mirror_-_Playtest.jpg", summary: "Cooper, an adventurous American backpacker, is traveling the world to escape responsibility after his father’s death. While in London, he signs up to test a revolutionary new augmented reality video game created by the gaming company SaitoGemu. The game implants a small device into his neck that connects to his nervous system, generating hyper-realistic experiences tailored to his fears. At first, Cooper is amused as he explores a haunted house simulation with simple scares. But the game rapidly escalates, blending real memories with hallucinations. Monsters morph into people from his life, and he loses the ability to tell what’s real.  As Cooper’s terror grows, he begs for the test to stop, but the simulation traps him in deeper layers of false reality. Finally, it’s revealed that the entire horrifying experience, that from the house to his breakdown, it happened in an instant. The device malfunctioned due to interference from his phone, killing him almost immediately. In the end, Cooper finally called 'Mom'"},
        { title: "Black Mirror - S03E03 - Shut Up and Dance (2016) - 9.3", poster: "https://upload.wikimedia.org/wikipedia/en/a/a8/Black_Mirror_-_Shut_Up_and_Dance.jpg", summary: "A shy teenager named Kenny is secretly recorded through his laptop webcam while masturbating. Hackers threaten to release the footage unless he follows their escalating instructions. At first, the tasks seem like minor humiliations, but soon he’s paired with another blackmail victim, Hector, a married man caught trying to cheat on his wife. Together, they are forced to carry out increasingly criminal acts such as delivering suspicious packages, robbing a bank, and finally being ordered to fight another blackmail victim to the death. Kenny kills his opponent, only to discover the hackers leak his video anyway. The final reveal exposes why Kenny was targeted: his “private” video wasn’t innocent, because he had been watching child pornography."},
        { title: "Black Mirror - S03E04 - San Junipero (2016) - 7.9", poster: "https://upload.wikimedia.org/wikipedia/en/e/e3/Black_Mirror_-_San_Junipero.jpg", summary: "In 1987, the shy and awkward Yorkie visits the lively seaside party town of San Junipero, where she meets the outgoing and carefree Kelly. They connect quickly, though Kelly insists their romance stay casual. Over repeated visits, sometimes in different time periods, it’s revealed that San Junipero isn’t real but a simulated reality where elderly or deceased people can upload their consciousness. In the real world, Yorkie is a woman who has been paralyzed since a car accident in her youth, and Kelly is an elderly widow in a nursing home. Yorkie plans to permanently upload into San Junipero, but Kelly hesitates, since her husband chose not to, and she fears betraying his memory. Ultimately, Kelly decides she wants to keep living and loving with Yorkie. After her real body passes away, she joins Yorkie in San Junipero. The episode closes on them together in the simulation, finally free and happy."},
        { title: "Black Mirror - S04E02 - Arkangel (2017) - 8.8", poster: "https://upload.wikimedia.org/wikipedia/en/thumb/b/be/Black_Mirror_S04E02_-_ArkAngel.png/250px-Black_Mirror_S04E02_-_ArkAngel.png", summary: "Single mother Marie panics after briefly losing sight of her young daughter, Sara. To ease her fears, she agrees to have a high-tech implant called Arkangel placed in Sara’s brain. The system allows Marie to track Sara’s location, monitor her health, and even filter out disturbing sights and sounds from her perspective. At first, it seems protective, but as Sara grows, the censorship warps her experiences, she cannot perceive violence, blood, or danger, leaving her naive and socially awkward. Marie later deactivates the filter, but the implant continues transmitting Sara’s activities. As a teenager, Sara experiments with drugs, sex, and independence. Unable to resist, Marie spies on her through Arkangel and intervenes in secret ways, eventually exposing Sara’s private life and humiliating her. When Sara discovers her mother’s surveillance, she explodes in anger, brutally beating Marie with the Arkangel tablet before running away, leaving her mother injured and alone."},
        { title: "Black Mirror - S02E07 - White Christmas (2014) - <b>Perfect Score</b>", poster: "https://upload.wikimedia.org/wikipedia/en/thumb/1/1e/Black_Mirror_-_White_Christmas.jpg/250px-Black_Mirror_-_White_Christmas.jpg", summary: "The story unfolds in three interwoven segments, told by two men, Matt (Jon Hamm) and Joe (Rafe Spall), who are stuck together in a remote snowy outpost during Christmas. Matt’s Story (Part 1 – Dating Coach) Matt once ran a secret side business where he used eye-implant technology to coach men during live dates. He guided clients in real time, helping them seduce women. But when one client’s date went horribly wrong, ending in death, the operation was exposed—destroying Matt’s life and family. Joe’s Story (Part 2 – Blocked) Joe confesses why he’s in the cabin: his fiancée Beth used “blocking” technology to cut him out of her life entirely—he couldn’t see or hear her. Years later, he stalked her anyway and discovered she had a child. When Beth died in an accident, Joe confronted her father, who was caring for the little girl. In a drunken rage, Joe caused Beth’s father to collapse and left the child—who turned out not to be his biological daughter—alone to die in the snow. Final Twist (Part 3 – The Twitst) It’s revealed the “Joe” in the cabin is actually a cookie interrogation—a digital copy of Joe’s mind. Matt had been working with police to extract Joe’s confession. Matt is released, but branded as a sex offender for his past crimes, meaning everyone in society can see and block him forever. Meanwhile, Joe’s cookie is left running in accelerated time, trapped for millennia of isolation within seconds of real life."},
        { title: "Black Mirror - S01E02 - Fifteen Million Merits (2011) - 8.8", poster: "https://upload.wikimedia.org/wikipedia/en/thumb/c/cc/Black_Mirror_-_Fifteen_Million_Merits.jpg/330px-Black_Mirror_-_Fifteen_Million_Merits.jpg", summary: "In a dystopian future, people live in a closed society where they generate energy by pedaling stationary bikes. Their labor earns them “merits”, a digital currency used to buy food, virtual goods, or access entertainment. The protagonist, Bing, is disillusioned with the system. After his brother dies, Bing inherits 15 million merits. He meets Abi, a kind young woman with a beautiful singing voice, and convinces her to audition for the talent show “Hot Shot.” He believes she can break free of the cycle. However, once Abi is on stage, the judges pressure her into joining the pornography industry instead of pursuing music. To Bing’s horror, she accepts. Crushed, Bing spends all his remaining merits on another “Hot Shot” audition. On stage, instead of performing, he delivers a furious, emotional rant against the system while holding a shard of glass to his neck, threatening suicide. The judges, instead of resisting, applaud his authenticity and offer him his own show where he rants weekly. In the end, Bing accepts. He lives in a larger, more luxurious cell with a view of nature on his screen, but it’s still artificial. He has traded one cage for another."},
        { title: "Black Mirror - S02E01 - Be Right Back (2013) - 8.6", poster: "https://upload.wikimedia.org/wikipedia/en/thumb/9/97/Be_Right_Back.jpg/250px-Be_Right_Back.jpg", summary: "Martha and her boyfriend Ash are deeply in love, but their life together is cut short when Ash dies suddenly in a car accident. Martha is devastated by grief. A friend introduces her to a new service that uses Ash’s digital footprint, his social media, texts, emails, and voice recordings, to create an AI version of him. At first, Martha is hesitant, but she begins texting “Ash” and is comforted by how much the AI resembles him. She upgrades to the next stage: a synthetic body, an android made to look and sound exactly like Ash. At first, the illusion brings comfort, but over time Martha grows frustrated. The android lacks the small flaws, spontaneity, and depth that made the real Ash human. When she tries to test his emotional authenticity by asking him to “leave” or show anger, he can only comply in a programmed, shallow way. Eventually, Martha locks the android away in her attic, unable to fully let go but also unable to accept him as a real replacement. Years later, her daughter knows of “Ash” as a strange presence kept upstairs, preserved like a living ghost."},
    ]
    },
    {
    name: "Game of Thrones: Season 1 (2011) - In Progress",
    episodes: [
        { title: "S01E01 - Winter Is Coming - 9.4", poster: "https://m.media-amazon.com/images/M/MV5BYjc1ZTg3YWItNTRiNC00NGY0LTg0MDAtOGZhNjZlMmIwNDMzXkEyXkFqcGc@._V1_QL75_UX400_.jpg", summary: "Beyond the Wall, Night’s Watch rangers encounter White Walkers; one survivor flees and is executed by Ned Stark for desertion. In Winterfell, Ned rules as Warden of the North with his wife Catelyn and children Robb, Sansa, Arya, Bran, and Rickon, along with his illegitimate son Jon Snow. They discover orphaned direwolf pups, one for each Stark child. King Robert Baratheon arrives with Queen Cersei, asking Ned to replace the recently deceased Jon Arryn as Hand of the King. Robert proposes betrothing Sansa to Prince Joffrey. Across the Narrow Sea, exiled Viserys Targaryen marries off his sister Daenerys to Khal Drogo, hoping to gain an army to reclaim the Iron Throne. Bran stumbles upon Cersei and Jaime Lannister’s incest, then Jaime pushes him from a tower."},
        { title: "S01E02 - The Kingsroad - 9.8", poster: "https://m.media-amazon.com/images/M/MV5BMjE3MDQ2MDI0OV5BMl5BanBnXkFtZTcwMjIyMzkxNA@@._V1_QL75_UX145_.jpg", summary: "Bran lies comatose after his fall. Jon Snow departs for the Wall, gifting Arya a small sword, Needle. Tyrion Lannister joins him, traveling north. On the Kingsroad, Joffrey bullies Arya’s friend; Arya fights back. When Nymeria attacks Joffrey, Arya drives her away to save her life. Cersei demands retribution—Arya’s direwolf is gone, so Sansa’s wolf, Lady, is executed instead. Ned reluctantly carries out the killing. Meanwhile, Daenerys begins her life among the Dothraki; Drogo is distant, but she begins learning to adapt to her new role."},
        { title: "S01E03 - Lord Snow - 9.0", poster: "https://m.media-amazon.com/images/M/MV5BOGVkMjU4M2MtZmRkYy00OWIwLTk3NmQtZDE0ZjliOTYxYjk0XkEyXkFqcGc@._V1_QL75_UX383_.jpg", summary: "Ned, Sansa, and Arya arrive in King’s Landing. Arya trains secretly with Syrio Forel, a Braavosi swordmaster. Ned learns the court is a web of scheming led by Varys, Littlefinger, and Pycelle. At the Wall, Jon trains but bullies weaker recruits until Tyrion reminds him of his own outsider status. Jon befriends Samwell Tarly, a cowardly new recruit. In Essos, Daenerys grows more confident, asserting herself with Drogo and beginning to challenge Viserys’ abusive control. Bran awakens from his coma, paralyzed from the waist down."},
        { title: "S01E04 - Cripples, Bastards, and Broken Things - 9.0", poster: "https://m.media-amazon.com/images/M/MV5BYTkxMWZhOTQtNDA2Yi00ZDNmLTg5OWMtMjBiZTliZDcwYTIxXkEyXkFqcGc@._V1_QL75_UX145_.jpg", summary: "Tyrion provides Bran with a saddle design so he can ride despite his paralysis. Jon protects Sam from brutal training, gaining loyalty from his fellow recruits. Ned investigates Jon Arryn’s death, discovering he was researching the Baratheon family lineage. At a tourney, Ser Hugh is killed under suspicious circumstances. Viserys’ frustrations boil over when Daenerys shows her authority as khaleesi, striking him. Across Westeros, Catelyn learns Tyrion may have been behind Bran’s fall after finding a dagger she believes is his."},
        { title: "S01E05 - The Wolf and the Lion - 9.1", poster: "https://m.media-amazon.com/images/M/MV5BNTczMmNmNTYtZGFiMS00ZmUzLTljODYtM2E0MGI4YjMwZTQwXkEyXkFqcGc@._V1_QL75_UX327_.jpg", summary: "Robert learns of Daenerys’ pregnancy and insists she be assassinated; Ned refuses to condone it and resigns as Hand. Tensions rise between him and Robert. In the Vale, Catelyn captures Tyrion, accusing him of trying to kill Bran. At the Eyrie, her sister Lysa Arryn imprisons him. In King’s Landing, political intrigue deepens as Renly and Loras Tyrell plot together. The Mountain goes berserk at the tourney, and Sandor “The Hound” Clegane saves lives by stopping him."},
        { title: "S01E06 - A Golden Crown - 9.3", poster: "https://m.media-amazon.com/images/M/MV5BZjFjMWU1M2YtOGJiYS00MGVjLWE0MmEtZmEzNTM5ZmZlMTNkXkEyXkFqcGc@._V1_QL75_UX328_.jpg", summary: "At the Eyrie, Tyrion demands trial by combat, and sellsword Bronn fights for him, winning his freedom. Ned returns as Hand after Robert is injured in a hunt. Investigating further, Ned confirms that Cersei’s children are not Robert’s but Jaime’s. In Essos, Viserys’ desperation peaks—he threatens Daenerys but Drogo kills him by pouring molten gold on his head, granting him the “crown” he craved."}
    ]
    }


]



mongoose.connection.once('open', () => {
  Series.deleteMany({}).then(() => {
    Series.insertMany(seriesArray)
      .then(() => console.log("TV series seeded!"))
      .catch(err => console.error(err));
  });

  app.get('/api/series', async (req, res) => {
    const series = await Series.find();
    console.log('Series from DB:', series);
    res.json(series);
  });
  app.get('/api/movieseries', async (req, res) => {
    const series = await MovieSeries.find();
    res.json(series);
  });

  app.listen(3000, () => console.log('Server running on port 3000'));
});